#cloud-config

hostname: ros-base

rancher:
  network:
    interfaces:
      br0:
        bridge: true
        dhcp: true
      eth0:
        bridge: br0

ssh_authorized_keys:
	-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCv1A2ZZg928LW6gseZrG5qjHc4I+QNdZm8VGXcT9SJgFnmqPylXvINHUhMrLF7MA8lySNeE5seMrKImMpU/aS3LCs4+Q5LHZJgRVZcvuhwLqpGtcrIFCAqshQd4UpWYKFWxPN8X39fdwWk03CRulL07yKmaY8AtBooxot5tFVS6TTNivU7Iz5iCLqBYP8ytH7Xw3vU6ec4duZWH5R6jbQrhnq9szl8/1hE5FclrB17AHKsx5UL5TiqY/ir3ViM6wO7ybCqAimFjdhBx/pAA9T93CzL6ixAS6+11rIUMu6LASYCb8GnLA2t9xyyiWlVBrIO6pReA+84gNWUOzOchUyOsFZ6nUAfdQ8Pv1dF20yn8Dr1+bG3ssOK00Tb9JCXcdiW1VWpqhCN7fHBJVQXWNBZkK1zU9jv9p3M2zQjQTV0cWnIek17Skq1j5CWN+2zhTLS8Bj0A8l0Xky0ivXAyjpgLFIWgTBBfOVpPnJp3sXNnMQtTo/H+RlTqI3FKyCurAgWnfgY6Q6jkgpWiJxJ7tl6NtidzAp5i7kw4j0jvJZBVvKiMU7kJce6Qu/MnBsmsh6UZldPXNs67w3ec9xcbs27OP1wB+di5diCAmpUb9N6oTGFbu7oo8YR+WAfmXcF6yFhiRZ5xHJ0gvFT79GDl0e1UvDssGHdtv+AL82+jqSlww== michael@mmccabe.ddns.net
